### ISSUE TITLE
Why does it default to AVI rather than MKV or such?

### ISSUE THREAD

**Issue by colemickens** [russelltg/wl-screenrec#12]
I was rather surprised to see this output an AVI. I haven't seen an AVI in the wild for ages. Is there a reason for using it over MKV?

**Comment by russelltg** [comment]
Yeah, great question--avi was just the first container format I got to work (for details of ffmpeg being tricky to use), but they should all work now.

I generally use it with mp4 for good compatibility

**Comment by russelltg** [comment]
Is there a reason you'd choose mkv over mp4 for default?

**Comment by colemickens** [comment]
I think I'm used to MKV from other video purposes where HEVC is used, but I don't know if that's relevant here. I'm not sure I could offer reasoning for one over the other.

**Comment by russelltg** [comment]
I see--ffmpeg lists AVC as the default codec for mkv and currently this package only supports AVC. 

Would you benefit from HEVC support? I'm happy to add it if there's interest.

**Comment by russelltg** [comment]
Added support for other codecs and changed default to mp4

**Comment by colemickens** [comment]
Thanks @russelltg !
