### ISSUE TITLE
Desktop Audio

### ISSUE THREAD

**Issue by Shinyzenith** [russelltg/wl-screenrec#18]
Would it be possible to record desktop audio with wl-screenrec?

**Comment by Shinyzenith** [comment]
I'm willing to work on patches if extra help is needed.

**Comment by russelltg** [comment]
Yeah, this is definitely doable and I had already worked on it a little. Should get time sometime in the next few weeks

**Comment by russelltg** [comment]
Take a peek at the `audio` branch--I need to review it a bit more before merging it into main but it's working for me
