### ISSUE TITLE
Fails to build on FreeBSD non-x86_64 or any other BSD

### ISSUE THREAD

**Issue by jbeich** [russelltg/wl-screenrec#21]
Regressed by bbedef7fce69. From [error log](https://github.com/russelltg/wl-screenrec/files/12135332/wl-screenrec-s20230720.log):
```
[drm-sys 0.4.0] thread 'main' panicked at 'No prebuilt bindings for target OS `freebsd` and/or architecture `x86`. Try `use_bindgen` feature.', drm-rs-dda0bfb9ab3bfc43b23bb756492d19e64a1a467d/drm-ffi/drm-sys/build.rs:187:9
[drm-sys 0.4.0] stack backtrace:
[drm-sys 0.4.0]    0: rust_begin_unwind
[drm-sys 0.4.0]    1: core::panicking::panic_fmt
[drm-sys 0.4.0]    2: build_script_build::main
[drm-sys 0.4.0]    3: core::ops::function::FnOnce::call_once
```
wl-screenrec already uses bindgen via `ffmpeg-sys-next` but `drm-sys` uses pre-generated bindings despite supporting bindgen.

**Comment by jbeich** [comment]
FWIW, FreeBSD has GPU drivers (for Wayland) on i386 (i915, radeon, amdgpu), aarch64 (amdgpu, panfrost), powerpc64 (amdgpu).

**Comment by russelltg** [comment]
Hmm--I tried to be careful and not break the BSD build--it builds fine for me...in the branch of drm-rs that I pushed there are freebsd bindings....

**Comment by russelltg** [comment]
I may replace `drm-rs` with a manual binding though as I only rely on a single function, which would fix this issue

**Comment by jbeich** [comment]
I confirm, builds and works fine on FreeBSD i386.
