### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Zenbin-bash** [russelltg/wl-screenrec#36]
![231117_05h33m21s_screenshot](https://github.com/russelltg/wl-screenrec/assets/105939071/615c8b21-4298-469b-b666-19e3e4a35185)

I dont know what happening, can you help me to fix thiis

**Comment by russelltg** [comment]
You don't have vappi setup correctly it seems. Follow your distributions instructions.

If they don't help, send info on your distribution and hardware setup, as well as your `vainfo` output so I can help diagnose.

**Comment by Zenbin-bash** [comment]
how can i setup my vappi?

**Comment by russelltg** [comment]
Please re-read my previous comment, as it seems you haven't consulted your distributions documentation or provided me any info required to diagnose.
