### ISSUE TITLE
`wl-screenrec` causes GPU to fail, compositor crashes

### ISSUE THREAD

**Issue by fufexan** [russelltg/wl-screenrec#44]
I've tried switching from `wf-recorder` to `wl-screenrec`, but when I've tried recording, weird things started happening:

I ran the command
```console
$ wl-screenrec -g "$(slurp -d)" --low-power off
```

Used `--low-power off` because I got this error when running without it
```
Using output eDP-1
Opening libva device from DRM device /dev/dri/renderD128
[h264_vaapi @ 0x560336d52400] No usable encoding entrypoint found for profile VAProfileH264High (7).
failed to open encoder in low_power mode (Function not implemented), trying non low_power mode. if you have an intel iGPU, set enable_guc=2 in the i915 module to use the fixed function encoder. pass --low-power=off to suppress this warning
[h264_vaapi @ 0x560336d52400] Driver does not support some wanted packed headers (wanted 0xd, found 0).
[h264_vaapi @ 0x560336d52400] Driver does not support packed sequence headers, but a global header is requested.
[h264_vaapi @ 0x560336d52400] No global header will be written: this may result in a stream which is not usable for some purposes (e.g. not muxable to some containers).
```

After a few seconds where the program kept saying "0 FPS", my monitors froze, then they turned black, displayed the static image again, and my compositor (Hyprland) crashed.

Looking in `dmesg` I found this https://gist.github.com/fufexan/74b6b2e1b46ba220c0d26aaafbf62094.

#### System info
`wl-screenrec`: `0.1.0`
`hyprland`: `0.32.3`
`mesa`: `23.1.9`
NixOS Unstable `24.05.20231129.e92039b (Uakari)`
CPU/GPU: AMD Ryzen 7 5800U with Radeon Graphics

Let me know how I can help further.

**Comment by russelltg** [comment]
What a wild world, this is an interesting one!

I highly doubt this is due to an issue in wl-screenrec, but hopefully we can get to the bottom of it. What's your kernel verison? Can you try:

1. `wf-recorder -c h264_vaapi -d /dev/dri/renderD128`
2. updating `mesa`
3. updating your kernel

**Comment by russelltg** [comment]
Could it be possible that you're hitting https://gitlab.freedesktop.org/drm/amd/-/issues/2384?
