### ISSUE TITLE
Visual glitch when recording a video

### ISSUE THREAD

**Issue by bluebyt** [russelltg/wl-screenrec#45]
I have one small problem, a visual glitch when recording a video.
I really want to use wl-screenrec, because the quality of the video is better then wf-recorder. (But I dont have this problem with wf-recorder)

You can see the visual glitch on the video at the beginning of the video:
[Video](https://streamable.com/xn4om8)

[vainfo](https://pastebin.com/k9J660XB)

[wl-screenrec -v](https://pastebin.com/63ue5kM4)

Hardware:
Intel CoffeeLake-S GT2 [UHD Graphics 630] 9th generation Core

I try to set enable_guc=2, maybe that will help to solve the problem, but for some reason it doesn't loaded.
When I do this: "sudo dmesg | grep -i guc"  I see nothing in the term 
But according to the Arch wiki that should work.
[Arch wiki](https://wiki.archlinux.org/title/Intel_graphics)

**Comment by russelltg** [comment]
Do you get this issue with `wf-recorder -c h264_vaapi -d /dev/dri/renderD128`?

**Comment by bluebyt** [comment]
No I dont have this issue with this command `wf-recorder -c h264_vaapi -d /dev/dri/renderD128`

With wl-screenrec it happen in average 2 times per one minutes of a video.

**Comment by russelltg** [comment]
If you increase the bitrate does it happen?  `--bitrate`

**Comment by bluebyt** [comment]
I am not able to reproduce the problem now, may its because Mesa Intel drivers update to version 24.0.
I will continue to investigate.

**Comment by russelltg** [comment]
Closing as it appears fixed. Reopen if you see it again
