### ISSUE TITLE
Geometry positioning ignored, screen recording starts at top left no matter what

### ISSUE THREAD

**Issue by ThatOneCalculator** [russelltg/wl-screenrec#52]
As the title says, doing something like `wl-screenrec -g "$(slurp)" -f "$HOME/Videos/screenrec_$(date +'%s').mp4" --low-power=off` and having `$(slurp)` be a region like `1528,156 1110x712` gets the size right but completely ignores the positioning, leaving it to record that size at the top left.

**Comment by ThatOneCalculator** [comment]
Actually, even after reverting it, the behavior still happens, so I'm not sure what's causing it...

**Comment by russelltg** [comment]
That commit doesn't ignore x and y, it just removes the cast as it's not needed anymore

**Comment by ThatOneCalculator** [comment]
Ah. Still not sure why it's being ignored in practice though.

**Comment by russelltg** [comment]
Yeah, it's super strange. My guess is an issue with your vaapi driver of sorts, but not entirely sure

**Comment by russelltg** [comment]
Probably a dup of #47, what does messing with exact give?

**Comment by ThatOneCalculator** [comment]
I can try the suggested fix in a couple hours. Also on Hyprland fwiw

**Comment by ThatOneCalculator** [comment]
I'll move the discussion over there since it's definitely a duplicate
