### ISSUE TITLE
Why wlr-screencopy instead of wlr-export-dmabuf?

### ISSUE THREAD

**Issue by CheerfulPianissimo** [russelltg/wl-screenrec#65]
From what I understand both of them can deal with dmabufs. Screencopy is more flexible with regards to the buffers it can deal with while wlr-export is simpler (and more performant?). 

This is not a feature request. I'm planning to work on a project around wayland screen capture and wanted to know if there were any caveats that would prevent a wlr-export-dmaubf version of wl-screenrec.

**Comment by russelltg** [comment]
It's a good question--I'm not particuarly familiar with wlr-export-dmabuf. One neat thing about wlr-screencopy is that I get to allocate my own surfaces, so don't have to deal with any complex importing process, and can just use the vaapi allocator. 

If I could just import the dmabuf's, which _should_ be possible, this may be higher performance as it may be able to avoid a copy, depending on how it's implemented in the compositor.

**Comment by russelltg** [comment]
This does at a glance seem possible via `VA_SURFACE_ATTRIB_MEM_TYPE_DRM_PRIME`/`VA_SURFACE_ATTRIB_MEM_TYPE_DRM_PRIME_2`, which ffmpeg does implement....

**Comment by CheerfulPianissimo** [comment]
Thanks for the clarification. The wl-screenrec codebase has been pretty informative so far.
