### ISSUE TITLE
choose audio encoding settings

### ISSUE THREAD

**Issue by SArpnt** [russelltg/wl-screenrec#71]
with ffmpeg -i i can see the audio format used in recordings is vorbis, which i assume is just the default that ffmpeg uses. i'd prefer it if i could record with libopus at a custom bitrate, or sometimes flac.

**Comment by russelltg** [comment]
I recently added --audio-codec (set codec, let ffmpeg decide encoder) and --ffmpeg-audio-encoder (hardcode which encoder to use) flags in master. Agree that a `--audio-bitrate` flag would be a good addition still.

**Comment by russelltg** [comment]
added `--audio-bitrate`. Open new issues for other feature requests
