### ISSUE TITLE
`--audio` flag failing with `--ffmpeg-muxer h264`

### ISSUE THREAD

**Issue by hraytilakhealthcare** [russelltg/wl-screenrec#73]
The video encoding is stellar, but for some reason, as soon as I try to add the `--audio` flag the program panics with the following message:
```
wl-screenrec --output DP-5 --low-power off --audio --audio-backend "pulse" --audio-device "alsa_input.usb-BOSS_Acoustic_Singer_LT-01.multichannel-input" --ffmpeg-muxer h264 -f derp.mkv
Opening libva device from DRM device /dev/dri/renderD128
thread 'main' panicked at src/audio.rs:175:10:
called `Option::unwrap()` on a `None` value
```

I tried various combinations of the `--audio`, `--audio-device` and `--audio-backend` flag with the same result. The issue is its simplest form with the following command:

`wl-screenrec --audio --ffmpeg-muxer h264 -f derp.mkv`

the presence of the `--ffmpeg-muxer h264` and `--audio` flag seem to make the program panic.

Tested on Arch `Linux LV-426 6.8.9-arch1-2`  with both git (commit e1c6de6e30a990dfef5e934966edd78df042425c) and released version.

**Comment by russelltg** [comment]
This should absolutely have a better error, but h264 isn't a container, it's a codec, so what you're asking for kinda is nonsense. Did you mean to pass `--codec`?

**Comment by russelltg** [comment]
So apparently h264 is indeed a ffmpeg format (container), but I highly doubt this is actually what you want considering you have the .mkv extension. I fixed the error message: `failed to create encoder(s): Container format h264 does not support audio!`. Lmk if there are any questions about this!

**Comment by hraytilakhealthcare** [comment]
Thanks for the clarification @russelltg and the error message is welcome. And yes, h264 is at this ambiguous place where it's both a video codec and a container.

My initial goal was to have a h264 video stream and a AAC audio stream sent to a remote box via rtmp. I didn't find a way to specify the audio format, but maybe I'm misunderstanding how to use the options.

My go-to test was the following command:
```
wl-screenrec --output DP-5 --low-power off --audio --ffmpeg-muxer h264  --filename "rtmp://the_url"
```

Let me know if there is a way to make it work I missed ?

**Comment by russelltg** [comment]
Okay, just pushed some new options that gets this working: `--ffmpeg-muxer-options`, `--audio-codec` and `--ffmpeg-audio-encoder`. This commandline now creates a rtmp stream for me: 

```
wl-screenrec --audio --ffmpeg-muxer flv --codec avc --ffmpeg-muxer-options "listen=1" --audio-codec aac --filename "rtmp://localhost:1234" 
```

Which I can then connect to with 

```
mpv rtmp://localhost:1234
```

**Comment by russelltg** [comment]
Let me know if this works for you, and I'll cut a release soon, there's a decent number of unreleased features these days.

**Comment by hraytilakhealthcare** [comment]
Thank you so much for the work @russelltg  ! I missed it because the issue was closed.

So it indeed works locally, there is sound and video working.

There are two caveats left. 

When I read the stream in local host, mpv reports : 
```
Audio/Video desynchronisation detected! Possible reasons include too slow
hardware, temporary CPU spikes, broken drivers, and broken files. Audio
position will not match to the video (see A-V status field).
Consider trying `--profile=fast` and/or `--hwdec=auto-safe` as they may help
```

Second, when trying to send the audio/video stream to an actual endpoint (twitch in my case), `wl-screenrec` reports:

```
[rtmp @ 0x610046453ac0] Cannot open connection tcp://live.twitch.tv:1935?listen&listen_timeout=-1000&tcp_nodelay=0
thread 'main' panicked at src/main.rs:1306:87:
called `Result::unwrap()` on an `Err` value: ffmpeg::Error(99: Cannot assign requested address)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
