### ISSUE TITLE
Broken as of latest FFMPEG update on Arch due to libavutil

### ISSUE THREAD

**Issue by ThatOneCalculator** [russelltg/wl-screenrec#78]
It seems that wl-screenrec wants `libavutil.so.58` but the latest version of ffmpeg provides `libavutil.so=59-64`

**Comment by ThatOneCalculator** [comment]
Nevermind, rebuilding/reinstalling fixed the issue

**Comment by abenz1267** [comment]
How did you get it to build? Trying to clean install from AUR, but always ending up with `error: could not compile `ffmpeg-next` (lib) due to 33 previous errors`.

Regards

**Comment by ThatOneCalculator** [comment]
I don't think ffmpeg-next works, just ffmpeg

**Comment by abenz1267** [comment]
But that's what's used in the crate: https://github.com/russelltg/wl-screenrec/blob/main/Cargo.toml#L32

Hence i was wondering how you built it.

**Comment by tesioai** [comment]
installing the -git version doesnt work for me

**Comment by russelltg** [comment]
@tesioai can you give me the build errors for -git? It builds fine for me on an updated arch linux.

**Comment by tesioai** [comment]
> @tesioai can you give me the build errors for -git? It builds fine for me on an updated arch linux.

it builds/installs fine, its just the libav version errors are the same, it didnt fix those errors for me

**Comment by russelltg** [comment]
Probably means you need to rebuild the package. If you use paru, pass the --rebuild flag

**Comment by tesioai** [comment]
> Probably means you need to rebuild the package. If you use paru, pass the --rebuild flag

yes that fixed it
