### ISSUE TITLE
Record last x seconds at all time?

### ISSUE THREAD

**Issue by Mateiadrielrafael** [russelltg/wl-screenrec#8]
Hi! I was curious how hard it would be to implement a feature that would have this program run at all times. Then when a command is run, the last X seconds are saved as a video (the X would be configure beforehand). This can be useful for saving short clips of stuff after you've had it happen. [Here](https://github.com/matanui159/ReplaySorcery) is an exmaple program which achieves something similar.

Thanks in advance!

**Comment by russelltg** [comment]
Let me know if that matches what you want, there's a new `--history` flag, and some usage in the readme

**Comment by Mateiadrielrafael** [comment]
Hi @russelltg , that looks like exactly what I was looking for! I couldn't get the package to compile on nixos, so I wasn't able to try it just yet, but I'll ask around for help with this in nix spaces and report back once I get it running.

**Comment by russelltg** [comment]
Feel free to open a PR updating the readme on how to install on NIX once you figure it out
