### ISSUE TITLE
[Question] Is it possible to record losslessly?

### ISSUE THREAD

**Issue by Yutsuten** [russelltg/wl-screenrec#81]
I'm considering changing from `wf-recorder` to `wl-screenrec`, but I'm used to record lossless videos like this:

```shell
wf-recorder -c libx264rgb -p crf=0 -f output.mp4
```

Is it possible to do something like this with `wl-screenrec` ?

**Comment by russelltg** [comment]
As of 680d9295fd13d47a0c119520c2b472fbd2017952


```bash
wl-screenrec --ffmpeg-encoder=libx264rgb --ffmpeg-encoder-options=crf=0
```

works (needed the --ffmpeg-encoder-options flag)

**Comment by Yutsuten** [comment]
Oh that's nice! I'll have a try on it later!

**Comment by Yutsuten** [comment]
I've made a comparison test by opening `vkcube` and `top` side by side and checked the CPU used in `top`.

| command | CPU usage |
| --- | --- |
| `wf-recorder -c libx264rgb -p crf=0` | 9~10% |
| `wl-screenrec --ffmpeg-encoder=libx264rgb --ffmpeg-encoder-options=crf=0` | 18~19% |

I'm kinda surprised by this result. I was expecting `wl-screenrec` to consume less CPU. I guess this is probably related to how `libx264rgb` works though.

As a second experiment, I also tried using `wl-screenrec` without arguments and `wf-recorder -c h264_vaapi -d /dev/dri/renderD128`. Both had about the same CPU usage (0.1~0.2%), but in the recorded video the cube is "shaking"... For both... Probably I'm missing something in my system.

CPU: AMD Ryzen 5 5600X (12) @ 3.70 GHz
GPU: AMD Radeon RX 6600
