### ISSUE TITLE
[Question] will wl-screenrec support ext-image-capture-source-v1 and ext-image-copy-capture-v1?

### ISSUE THREAD

**Issue by Quackdoc** [russelltg/wl-screenrec#82]
are their any plans on supporting ext-image-capture-source-v1 and ext-image-copy-capture-v1 https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/124 now that it is merged?

**Comment by russelltg** [comment]
Awesome to see that was merged! Def will support once it's in sway.

**Comment by Quackdoc** [comment]
wayland protocols version has finally been tagged, so I'll post some PRs for various things for tracking, these are the only thing's I've found for compositors yet.

wlroots: PR - https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4545
cosmic-comp: PR - https://github.com/pop-os/cosmic-comp/pull/365
Hyprland: Issue - https://github.com/hyprwm/Hyprland/issues/7478
