### ISSUE TITLE
Streaming wl-screenrec output over TCP

### ISSUE THREAD

**Issue by poweredbypie** [russelltg/wl-screenrec#93]
Hi, I'm trying to hack up a low-latency method for using my phone as a screen extension over USB. I'd like to use wl-screenrec to grab a headless sway display, encode it, and then send it over a raw TCP stream to another program on my computer which will forward the packet through the USB connection. The following works with the ffmpeg CLI:
```sh
ffmpeg -vaapi_device /dev/dri/renderD128 -i <test> -vf 'format=nv12,hwupload' -c:v h264_vaapi -f mpegts 'tcp://127.0.0.1:8111'
```
I'd like to accomplish the same thing with wl-screenrec without writing the file to disk. I tried the following:
```sh
wl-screenrec --codec avc --ffmpeg-muxer mpegts -f 'tcp://127.0.0.1:8111'
```
But this spits out the following error:
```
failed to create encoder(s): Format mpegts does not support H264 codec
```
I'm fairly certain the error is wrong simply because the ffmpeg CLI worked fine, so I suspect it's how wl-screenrec is passing the parameters to ffmpeg. How would I accomplish this, or would a code change be warranted? I'm happy to contribute if necessary.

**Comment by russelltg** [comment]
Yeah, definitely strange (caught my eye for sure; my dayjob is dealing with h264 in mpegts so yes, definitely is a supported combo). 

I call `avformat_query_codec` to see if the muxer supports the codec first to give nicer error messages, but it returns false! If I remove the check it works fine though. 

I'll need to look and see if I can keep similar error messages without calling `avformat_query_codec`.

**Comment by poweredbypie** [comment]
> I call `avformat_query_codec` to see if the muxer supports the codec first to give nicer error messages, but it returns false! If I remove the check it works fine though.

`avformat_query_codec` returns this value for h264 + mpegts:
![image](https://github.com/user-attachments/assets/b823ce85-37a9-44b6-9b0f-52c07980b2a3)

It looks like it's because some combinations of containers and codecs aren't implemented, so the function returns `AVERROR_PATCHWELCOME`:
![image](https://github.com/user-attachments/assets/3b0b00c1-ddc5-4677-9e12-437be2b1929b)

Would it suffice to print a warning logging that ffmpeg isn't sure if the combination is compatible and proceed anyways?

**Comment by russelltg** [comment]
I think that's a idea.

**Comment by russelltg** [comment]
I read the docs more carefully and negative means "unknown" which I now just warn for
