### ISSUE TITLE
Save in chunks

### ISSUE THREAD

**Issue by 1over137** [russelltg/wl-screenrec#94]
I would like to use this to produce a long running scaled down recording to track my working time. What would be the best way to produce recordings for short segments (maybe 30s-10min) and save frequently to avoid data corruption?

**Comment by russelltg** [comment]
I'm not sure I totally follow the feature request. How do these segments get delimited? How are they named? Are there any signals involved?

**Comment by 1over137** [comment]
> How do these segments get delimited? How are they named?

The program will need to create new names for each new file, but it can just be a filename plus the timestamp.

> Are there any signals involved?

Not necessarily. The idea is to pass in a flag --save-every 30 to write a new file every 30s.

I assume it can also accept a signal to write immediately, though.

**Comment by PartyWumpus** [comment]
> save frequently to avoid data corruption

As far as I can tell, wl-screenrec writes to the file as it goes. Just save to a format that can survive missing end bytes, like MKV and it'd be fine. OBS uses mkv for this reason.

**Comment by russelltg** [comment]
@1over137 is what @PartyWumpus an acceptable solution? If so I'll go ahead and close this

**Comment by 1over137** [comment]
Is there a good way to auto stop the recording after a defined amount of time?

**Comment by russelltg** [comment]
Yeah, this is trivially scriptable

```bash
wl-screenrec &
pid=$!
sleep 10
kill -INT $pid
```
