### ISSUE TITLE
--no-hw option seems to not work

### ISSUE THREAD

**Issue by 1over137** [russelltg/wl-screenrec#97]
`wl-screenrec --no-hw --ffmpeg-encoder libx265 -v -f $(date +%Y%m%d-%H%M%S).mkv`

It seems that it is still attempting to use hw encoding. This produces the following output:
```
12:54:12 [INFO] output probe complete: {ObjectId(wl_output@6, 6): Some(OutputInfo { name: "HDMI-A-1", loc: (0, 0), logical_size: (3440, 1440), size_pixels: (3440, 1440), refresh: Rational(99982/1000), output: WlOutput { id: ObjectId(wl_output@6, 6), version: 4, data: Some(ObjectData { .. }), backend: WeakBackend { inner: WeakInnerBackend { state: (Weak) } } }, transform: Normal })}
12:54:12 [INFO] Using output HDMI-A-1
12:54:12 [INFO] capture pixel format is XR24
12:54:12 [INFO] encode pixel format is Sw(YUV420P)
Opening libva device from DRM device /dev/dri/renderD128
[Parsed_scale_vaapi_1 @ 0x55e2ca7cf980] Hardware does not support output format yuv420p.
[Parsed_scale_vaapi_1 @ 0x55e2ca7cf980] Failed to configure output pad on Parsed_scale_vaapi_1
thread 'main' panicked at src/main.rs:1764:18:
called `Result::unwrap()` on an `Err` value: ffmpeg::Error(22: Invalid argument)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by russelltg** [comment]
Yeah, I've had a bunch of reports like this, I definitely chose a bad name for that param. That param just disables HW encoding, but still does HW pixel allocation/pixel format conversion/crop. 

In other words, in your cmdline `--no-hw` is redundant as you've already specified an encoder that doesn't support vaapi surfaces. 

If your machine doesn't support HW pixel format conversion, there is no real benefit of wl-screenrec over wf-recorder, which aims to be more generally compatible. 

Maybe when vulkan encode stuff works (check back in in a year, haha) more hardware will be supported.
